version: '3.7'
services:
  redis:
    image: redis:latest
    container_name: job_dispatcher_redis_test
    hostname: redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
  mysql:
    image: mysql:latest
    container_name: job_dispatcher_mysql_test
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${SQL_PASSWORD}
      MYSQL_DATABASE: ${SQL_DATABASE}
      MYSQL_USER: ${SQL_USER}
      MYSQL_PASSWORD: ${SQL_PASSWORD}